### ISSUE TITLE
Individual Project Plan Checkpoint 1 ready for review

### ISSUE THREAD

**Issue by cometazzi** [cometazzi/DocumentMgmtSys#1]
@pawaitemadisoncollege 

Hi Paula, I believe I'm on the right track here, but I am submitting a little early in case there's a chance you have time to look it over and make an assessment.  I'll let you decide if an online chat through here or slack is sufficient, or if it's better for us to talk via teams or similar.

**Comment by pawaitemadisoncollege** [comment]
Hi @cometazzi!

First, that electronic component inventory system that you referenced in your reflection sounds like a great idea, it could absolutely work as an Ent Java project.  If you want to shift gears, do it. I can't see any reason at all that it wouldn't meet the requirement for the course, and the energy you have around that idea seems better than the DMS :) 

That said, I'm going to go ahead reviewing and providing feedback on the current idea, but know that if you want to revise to a different idea, I'm happy to review that too!

**Problem statement** 

Does a good job clearly explaining the problem and the solution. 

- [ ] readme.md should be at the root of your project, rather than within source - this is like the home page for your repository we want that to be the first thing anyone browsing your repo sees.

- [ ] This looks familiar, are you really planning to investigate all of these? Hibernate search might make sense, but I'm not sure they all do. That's a lot to take on ;) 
"Tech I'd like to explore as part of this work
CI tools in AWS
Materialize
Google Maps API
Hibernate Validator
Hibernate Search"

- [ ] Some links on the readme are broken. Fix or remove the ones you won't be using.

**User stories w/ MVP stories identified** Your users stories are clear and well-written following the best practices for user stories. They clearly communicate what your application will do. Your MVP stories seem to what's needed for the ent java project requirements like crud, and multiple tables with more than one one-to-many relationship. I think you've done a good job scoping the project to what's doable this semester!

- [ ] Should there be a way to "crud" the categories or departments, or will this be sort of freeform data in the user attributes?

- [ ] Thinking about a web service or api that could be used in your project, I  think there are a few possibilities, one is hibernate search or another search library for searching your documents. Another could be javamail or similar - the admin could get an email or some notification when a new user signs up - this way the admin could set up that user's department/groups. 

**Wireframes**. Good work on these! The wireframes clearly communicate what each page will do and seem to match up with the user stories above.

- [ ] Something to know is that we'll be using AWS cognito for sign up/sign in capability, so there are some screens that you may not have to worry about as they can be provided by Cognito itself.  We'll learn more about this in week 7.

** Project Plan** A good start!

- [ ] There's reference to Trails - this should be updated to reflect your project. 

- [ ] I recommend at least identifying which user story you plan to work on each week.  Chatgpt can be helpful brainstorming tasks if you are having trouble coming up with them. I think the more detailed you can be the better. What do you think about creating a task for each story to decide which jsp/s, controllers, entities, tables you'll need for that story.  Revising the plan could be a task on the plan itself (woah!)

**Reflection/Time log** Keep up the good work with this. Document all time spent in class, not just time on your indie project. This helps us both evaluate what might need more or less time!

**Comment by cometazzi** [comment]
Hi @pawaitemadisoncollege 

You're an awesome teacher and all, but I'm not sure how you picked up on the 'energy' around the electronics parts catalogue application.  I'm considering about my options, which is why I haven't completed the above tasks.  I do know I can't dilly-dally too long, and that if I'm going to leap it's now or not.

**Comment by pawaitemadisoncollege** [comment]
lol @cometazzi! If you'd find it helpful to [meet](https://outlook.office.com/bookwithme/user/07f43c2cfb044f029d40c05eb2c902c5@madisoncollege.edu?anonymous&ep=pcard) to chat through some ideas, feel free to schedule some time!
